# Generated by Django 4.2.6 on 2023-10-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_todo', '0002_todo_created_at_todo_status_todo_title_alter_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='todo',
            name='member',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='Low', max_length=10),
        ),
    ]
