# Generated by Django 4.2.6 on 2023-10-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_todo', '0003_remove_todo_status_todo_member_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='Not Done', max_length=10),
        ),
    ]
